spring.application.name=sender_service
server.port=8093


#RabbitMQ local properties
spring.rabbitmq.host=localhost
spring.rabbitmq.virtual-host=vhost
spring.rabbitmq.username=user
spring.rabbitmq.password=sa

rabbitmq.queues.value=firstQueue
rabbitmq.exchanges.value=mainExchange

