spring.application.name=first_receiver_service

server.port=8094

#RabbitMQ first receiver service local properties
spring.rabbitmq.host=localhost
spring.rabbitmq.virtual-host=vhost
spring.rabbitmq.username=user
spring.rabbitmq.password=sa

rabbitmq.queue.producer=secondQueue
rabbitmq.queues.listener=firstQueue