spring.application.name=data_storage_service

server.port=8097

# RabbitMQ properties
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.virtual-host=vhost
spring.rabbitmq.username=user
spring.rabbitmq.password=sa

rabbitmq.queues.listener=furthQueue

# PostgreSQL properties
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver